### PR TITLE
Changes/graph ql

### PR DESCRIPTION
**Pull request by Bijan137**
Modified plugin to use GraphQl

### CODE REVIEW

**Comment by narthur** [comment]
@Bijan137 Just created the `ready-for-internal` label for this repo. Add that label and request @mattleff and my reviews when you're ready to have our feedback. Thanks!

**Comment by Bijan137** [comment]
> @Bijan137 Just created the `ready-for-internal` label for this repo. Add that label and request @mattleff and my reviews when you're ready to have our feedback. Thanks!



> 

@narthur  I dont have the permission to add label to MR.
Screen Shot 2022-05-25 at 21 36 30

**Comment by narthur** [comment]
@Bijan137 My bad! I've added you and @bsalb as collaborators, and I'll go ahead and set the label and request our reviews this time.

**Review by narthur — CHANGES_REQUESTED** [review]
Can we remove the settings fields for the old APIs? Also, when I configure it with the GraphQL API, the list shortcode seems to fail to pull the sermons, and it shows an error in the console.

Screen Shot 2022-06-01 at 11 45 03 AM
Screen Shot 2022-06-01 at 11 44 54 AM

**Comment by Bijan137** [comment]
@narthur, still cannot add label to Pull Request.

**Review by narthur — APPROVED** [review]
Great work!

**Pull request merged**
